name: Publish Node.js Package

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm version ${{github.event.inputs.version}}
      - run: npx webpack
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
